<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>conf</string>
		<string>CONF</string>
		<string>.htaccess</string>
		<string>.HTACCESS</string>
		<string>.htgroups</string>
		<string>.HTGROUPS</string>
		<string>.htpasswd</string>
		<string>.HTPASSWD</string>
	</array>
	<key>name</key>
	<string>Apache Conf</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.apacheconf</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^(\s)*(#).*$\n?</string>
			<key>name</key>
			<string>comment.line.hash.ini</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.apacheconf</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.tag.apacheconf</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>string.value.apacheconf</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.apacheconf</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(&lt;)(Proxy|ProxyMatch|IfVersion|Directory|DirectoryMatch|Files|FilesMatch|IfDefine|IfModule|Limit|LimitExcept|Location|LocationMatch|VirtualHost)(\s(.+?))?(&gt;)</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.apacheconf</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.tag.apacheconf</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.apacheconf</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(&lt;/)(Proxy|ProxyMatch|IfVersion|Directory|DirectoryMatch|Files|FilesMatch|IfDefine|IfModule|Limit|LimitExcept|Location|LocationMatch|VirtualHost)(&gt;)</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>string.regexp.apacheconf</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>string.replacement.apacheconf</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?&lt;=(Rewrite(Rule|Cond)))\s+(.+?)\s+(.+?)($|\s)</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.status.apacheconf</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>string.regexp.apacheconf</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>string.path.apacheconf</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?&lt;=RedirectMatch)(\s+(\d\d\d|permanent|temp|seeother|gone))?\s+(.+?)\s+((.+?)($|\s))?</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.status.apacheconf</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>string.path.apacheconf</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>string.path.apacheconf</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?&lt;=Redirect)(\s+(\d\d\d|permanent|temp|seeother|gone))?\s+(.+?)\s+((.+?)($|\s))?</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.regexp.apacheconf</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>string.path.apacheconf</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?&lt;=ScriptAliasMatch|AliasMatch)\s+(.+?)\s+((.+?)\s)?</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.path.apacheconf</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>string.path.apacheconf</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?&lt;=RedirectPermanent|RedirectTemp|ScriptAlias|Alias)\s+(.+?)\s+((.+?)($|\s))?</string>
		</dict>


		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.core.apacheconf</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(AcceptPathInfo|AccessFileName|AddDefaultCharset|AddOutputFilterByType|AllowEncodedSlashes|AllowOverride|AuthName|AuthType|CGIMapExtension|ContentDigest|DefaultType|DocumentRoot|EnableMMAP|EnableSendfile|ErrorDocument|ErrorLog|FileETag|ForceType|HostnameLookups|IdentityCheck|Include|KeepAlive|KeepAliveTimeout|LimitInternalRecursion|LimitRequestBody|LimitRequestFields|LimitRequestFieldSize|LimitRequestLine|LimitXMLRequestBody|LogLevel|MaxKeepAliveRequests|NameVirtualHost|Options|Require|RLimitCPU|RLimitMEM|RLimitNPROC|Satisfy|ScriptInterpreterSource|ServerAdmin|ServerAlias|ServerName|ServerPath|ServerRoot|ServerSignature|ServerTokens|SetHandler|SetInputFilter|SetOutputFilter|TimeOut|TraceEnable|UseCanonicalName)\b</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.mpm.apacheconf</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(AcceptMutex|AssignUserID|BS2000Account|ChildPerUserID|CoreDumpDirectory|EnableExceptionHook|Group|Listen|ListenBacklog|LockFile|MaxClients|MaxMemFree|MaxRequestsPerChild|MaxRequestsPerThread|MaxSpareServers|MaxSpareThreads|MaxThreads|MaxThreadsPerChild|MinSpareServers|MinSpareThreads|NumServers|PidFile|ReceiveBufferSize|ScoreBoardFile|SendBufferSize|ServerLimit|StartServers|StartThreads|ThreadLimit|ThreadsPerChild|ThreadStackSize|User|Win32DisableAcceptEx)\b</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.access.apacheconf</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(Allow|Deny|Order)\b</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.actions.apacheconf</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(Action|Script)\b</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.alias.apacheconf</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(Alias|AliasMatch|Redirect|RedirectMatch|RedirectPermanent|RedirectTemp|ScriptAlias|ScriptAliasMatch)\b</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.auth.apacheconf</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(AuthAuthoritative|AuthGroupFile|AuthUserFile)\b</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.auth_anon.apacheconf</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(Anonymous|Anonymous_Authoritative|Anonymous_LogEmail|Anonymous_MustGiveEmail|Anonymous_NoUserID|Anonymous_VerifyEmail)\b</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.auth_dbm.apacheconf</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(AuthDBMAuthoritative|AuthDBMGroupFile|AuthDBMType|AuthDBMUserFile)\b</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.auth_digest.apacheconf</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(AuthDigestAlgorithm|AuthDigestDomain|AuthDigestFile|AuthDigestGroupFile|AuthDigestNcCheck|AuthDigestNonceFormat|AuthDigestNonceLifetime|AuthDigestQop|AuthDigestShmemSize)\b</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.auth_ldap.apacheconf</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(AuthLDAPAuthoritative|AuthLDAPBindDN|AuthLDAPBindPassword|AuthLDAPCharsetConfig|AuthLDAPCompareDNOnServer|AuthLDAPDereferenceAliases|AuthLDAPEnabled|AuthLDAPFrontPageHack|AuthLDAPGroupAttribute|AuthLDAPGroupAttributeIsDN|AuthLDAPRemoteUserIsDN|AuthLDAPUrl)\b</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.autoindex.apacheconf</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(AddAlt|AddAltByEncoding|AddAltByType|AddDescription|AddIcon|AddIconByEncoding|AddIconByType|DefaultIcon|HeaderName|IndexIgnore|IndexOptions|IndexOrderDefault|ReadmeName)\b</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.cache.apacheconf</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(CacheDefaultExpire|CacheDisable|CacheEnable|CacheForceCompletion|CacheIgnoreCacheControl|CacheIgnoreHeaders|CacheIgnoreNoLastMod|CacheLastModifiedFactor|CacheMaxExpire)\b</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.cern_meta.apacheconf</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(MetaDir|MetaFiles|MetaSuffix)\b</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.cgi.apacheconf</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(ScriptLog|ScriptLogBuffer|ScriptLogLength)\b</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.cgid.apacheconf</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(ScriptLog|ScriptLogBuffer|ScriptLogLength|ScriptSock)\b</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.charset_lite.apacheconf</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(CharsetDefault|CharsetOptions|CharsetSourceEnc)\b</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.dav.apacheconf</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(Dav|DavDepthInfinity|DavMinTimeout|DavLockDB)\b</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.deflate.apacheconf</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(DeflateBufferSize|DeflateCompressionLevel|DeflateFilterNote|DeflateMemLevel|DeflateWindowSize)\b</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.dir.apacheconf</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(DirectoryIndex|DirectorySlash)\b</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.disk_cache.apacheconf</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(CacheDirLength|CacheDirLevels|CacheExpiryCheck|CacheGcClean|CacheGcDaily|CacheGcInterval|CacheGcMemUsage|CacheGcUnused|CacheMaxFileSize|CacheMinFileSize|CacheRoot|CacheSize|CacheTimeMargin)\b</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.dumpio.apacheconf</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(DumpIOInput|DumpIOOutput)\b</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.env.apacheconf</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(PassEnv|SetEnv|UnsetEnv)\b</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.expires.apacheconf</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(ExpiresActive|ExpiresByType|ExpiresDefault)\b</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.ext_filter.apacheconf</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(ExtFilterDefine|ExtFilterOptions)\b</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.file_cache.apacheconf</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(CacheFile|MMapFile)\b</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.headers.apacheconf</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(Header|RequestHeader)\b</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.imap.apacheconf</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(ImapBase|ImapDefault|ImapMenu)\b</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.include.apacheconf</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(SSIEndTag|SSIErrorMsg|SSIStartTag|SSITimeFormat|SSIUndefinedEcho|XBitHack)\b</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.isapi.apacheconf</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(ISAPIAppendLogToErrors|ISAPIAppendLogToQuery|ISAPICacheFile|ISAPIFakeAsync|ISAPILogNotSupported|ISAPIReadAheadBuffer)\b</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.ldap.apacheconf</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(LDAPCacheEntries|LDAPCacheTTL|LDAPConnectionTimeout|LDAPOpCacheEntries|LDAPOpCacheTTL|LDAPSharedCacheFile|LDAPSharedCacheSize|LDAPTrustedCA|LDAPTrustedCAType)\b</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.log.apacheconf</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(BufferedLogs|CookieLog|CustomLog|LogFormat|TransferLog|ForensicLog)\b</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.mem_cache.apacheconf</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(MCacheMaxObjectCount|MCacheMaxObjectSize|MCacheMaxStreamingBuffer|MCacheMinObjectSize|MCacheRemovalAlgorithm|MCacheSize)\b</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.mime.apacheconf</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(AddCharset|AddEncoding|AddHandler|AddInputFilter|AddLanguage|AddOutputFilter|AddType|DefaultLanguage|ModMimeUsePathInfo|MultiviewsMatch|RemoveCharset|RemoveEncoding|RemoveHandler|RemoveInputFilter|RemoveLanguage|RemoveOutputFilter|RemoveType|TypesConfig)\b</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.misc.apacheconf</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(ProtocolEcho|Example|AddModuleInfo|MimeMagicFile|CheckSpelling|ExtendedStatus|SuexecUserGroup|UserDir)\b</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.negotiation.apacheconf</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(CacheNegotiatedDocs|ForceLanguagePriority|LanguagePriority)\b</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.nw_ssl.apacheconf</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(NWSSLTrustedCerts|NWSSLUpgradeable|SecureListen)\b</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.proxy.apacheconf</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(AllowCONNECT|NoProxy|ProxyBadHeader|ProxyBlock|ProxyDomain|ProxyErrorOverride|ProxyFtpDirCharset|ProxyIOBufferSize|ProxyMaxForwards|ProxyPass|ProxyPassReverse|ProxyPreserveHost|ProxyReceiveBufferSize|ProxyRemote|ProxyRemoteMatch|ProxyRequests|ProxyTimeout|ProxyVia)\b</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.rewrite.apacheconf</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(RewriteBase|RewriteCond|RewriteEngine|RewriteLock|RewriteLog|RewriteLogLevel|RewriteMap|RewriteOptions|RewriteRule)\b</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.setenvif.apacheconf</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(BrowserMatch|BrowserMatchNoCase|SetEnvIf|SetEnvIfNoCase)\b</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.so.apacheconf</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(LoadFile|LoadModule)\b</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.ssl.apacheconf</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(SSLCACertificateFile|SSLCACertificatePath|SSLCARevocationFile|SSLCARevocationPath|SSLCertificateChainFile|SSLCertificateFile|SSLCertificateKeyFile|SSLCipherSuite|SSLEngine|SSLMutex|SSLOptions|SSLPassPhraseDialog|SSLProtocol|SSLProxyCACertificateFile|SSLProxyCACertificatePath|SSLProxyCARevocationFile|SSLProxyCARevocationPath|SSLProxyCipherSuite|SSLProxyEngine|SSLProxyMachineCertificateFile|SSLProxyMachineCertificatePath|SSLProxyProtocol|SSLProxyVerify|SSLProxyVerifyDepth|SSLRandomSeed|SSLRequire|SSLRequireSSL|SSLSessionCache|SSLSessionCacheTimeout|SSLUserName|SSLVerifyClient|SSLVerifyDepth)\b</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.usertrack.apacheconf</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(CookieDomain|CookieExpires|CookieName|CookieStyle|CookieTracking)\b</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.vhost_alias.apacheconf</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(VirtualDocumentRoot|VirtualDocumentRootIP|VirtualScriptAlias|VirtualScriptAliasIP)\b</string>
		</dict>

		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.php.apacheconf</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.property.apacheconf</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>string.value.apacheconf</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(php_value|php_flag)\b(\s+(.+?)(\s+(.+?))?)?\s</string>
		</dict>

		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.variable.apacheconf</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>variable.env.apacheconf</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>variable.misc.apacheconf</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>punctuation.variable.apacheconf</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(%\{)((HTTP_USER_AGENT|HTTP_REFERER|HTTP_COOKIE|HTTP_FORWARDED|HTTP_HOST|HTTP_PROXY_CONNECTION|HTTP_ACCEPT|REMOTE_ADDR|REMOTE_HOST|REMOTE_PORT|REMOTE_USER|REMOTE_IDENT|REQUEST_METHOD|SCRIPT_FILENAME|PATH_INFO|QUERY_STRING|AUTH_TYPE|DOCUMENT_ROOT|SERVER_ADMIN|SERVER_NAME|SERVER_ADDR|SERVER_PORT|SERVER_PROTOCOL|SERVER_SOFTWARE|TIME_YEAR|TIME_MON|TIME_DAY|TIME_HOUR|TIME_MIN|TIME_SEC|TIME_WDAY|TIME|API_VERSION|THE_REQUEST|REQUEST_URI|REQUEST_FILENAME|IS_SUBREQ|HTTPS)|(.*?))(\})</string>
		</dict>

		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.mime-type.apacheconf</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b((text|image|application|video|audio)/.+?)\s</string>
		</dict>

		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.helper.apacheconf</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(?i)(from|unset|set|on|off)\b</string>
		</dict>

		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.integer.apacheconf</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(\d+)\b</string>
		</dict>

		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.flag.apacheconf</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>string.flag.apacheconf</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.flag.apacheconf</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\s(\[)(.*?)(\])\s</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.apacheconf</string>
	<key>uuid</key>
	<string>8747d9e4-b308-4fc2-9aa1-66b6919bc7b9</string>
</dict>
</plist>
